name: Email
main: nmt.minecraft.chavezfk.Email.Email
version: 1.00
description: Email system for Minecraft between players who are online and offline

commands:
    message:
        description: Sends a message to a player
        usage: /message [player] [message]
        permission: Email.message
        permission-message: If you dont have permission there is an error....

permissions:
    message.*:
        description: gives access to ALL message command
        children:
            message.send: true
            message.inbox: true
            message.empty: true
            message.block: true
            message.unblock: true
    message.send:
        description: Allows you to send a message to a player
        default: true
    message.inbox: 
        description: Allows you to access your message inbox
        default: true
    message.empty:
        description: Allows you to empty your inbox
        default: true
    message.block:
        description: Allows you to block messages from a player
        default: true
    message.unblock:
        description: Allows you to unblock someone you blocked.
        default: true
